"""Central configuration for the VPN admin / control-plane.

Precedence (low -> high):
    built-in defaults  <  environment variables  <  /data/settings.json

The built-in defaults are GENERIC and contain NO secrets — real values come
from `.env` (written by the install wizard) and from the web "Settings" pages,
which persist edits into /data/settings.json (web wins). Never put secrets or
host-specific values here; they would leak into the public repo.

Nothing here talks to the network; importing this module is cheap and safe.
"""
from __future__ import annotations

import json
import os
import secrets
from functools import lru_cache

DATA_DIR = os.environ.get("VPN_DATA_DIR", "/data")
SETTINGS_FILE = os.path.join(DATA_DIR, "settings.json")

# ── built-in defaults (current box) ───────────────────────────────────────────
_DEFAULTS: dict = {
    # identity / branding  (real values come from .env / the install wizard)
    "brand": "MyVPN",
    "server_ip": "",

    # domains: list of {domain, role, proxied}
    #   role: admin | cdn | direct | apex   (apex = bare/www, reality serverName only)
    #   proxied: behind Cloudflare orange-cloud (CDN) or not
    # Empty by default — set by the wizard or the admin "Domains" page (settings.json).
    "domains": [],

    # subscription delivery
    "sub_https_base": "",
    "sub_mirrors": [],

    # reality (xray) — keypair is GENERATED by the wizard (`xray x25519`); never
    # shipped in the repo. render.py injects these from cfg at config-build time.
    "reality_public_key":  "",
    "reality_private_key": "",
    "reality_short_id":    "",
    # RealitySteal2 real-site steal target. Must be a host whose TLS handshake
    # completes through REALITY: www.microsoft.com does NOT (dies at Certificate,
    # ~9.6 KB chain via Akamai) and silently rejects every client.
    "reality_sni":         "gateway.icloud.com",
    "reality_port":        8443,

    # protocol endpoints
    "cdn_domain":    "",
    "hu_path":       "/probe",
    "direct_domain": "",
    "hy2_sni":       "",
    "tuic_sni":      "",
    "hy2_port":      443,    # sing-box hysteria2 (primary, UDP)
    "hy2_port_x":    8444,   # xray hysteria2 (secondary, UDP)
    "hy2_up_mbps":   50,
    "hy2_down_mbps": 120,
    "tuic_port":     9443,
    "tcp_port":      2080,

    # admin auth  (generated by the wizard; empty default = must be provisioned)
    "admin_user": "admin",
    "admin_pass": "",
    "secret_key": "",

    # health / telegram
    "health_token":  "",
    "tg_bot_token":  "",
    "host_thresholds": [30, 50, 80, 90],
    "user_thresholds": [50, 80],

    # provider-traffic widget (generic; HOSTKEY preset, credentials entered in admin)
    "provider": {
        "enabled": False,
        "name": "HOSTKEY",
        "auth_url":   "https://invapi.hostkey.ru/auth.php",
        "data_url":   "https://invapi.hostkey.ru/eq.php",
        "api_key":    "",
        "server_id":  "",
        # where to read numbers out of the provider's JSON response
        "used_field":  "trafficPeriodOut",   # GB used this period
        "limit_field": "limit_traffic",       # TB cap
        "limit_unit_tb": True,
        "bands_field": "limit_bands",
        "reset_field": "datePeriod",
    },

    # core control
    "xray_container":   "xray",
    "xray_api":         "127.0.0.1:10085",
    "singbox_container": "sing-box",
    "singbox_clash_api": "127.0.0.1:9090",
    "nginx_container":  "nginx",

    # filesystem paths (inside the admin container)
    "xray_cfg":     "/etc/xray/config.json",
    "sing_box_cfg": "/etc/sing-box/config.json",
    "nginx_cfg":    "/etc/nginx/conf.d/default.conf",
    "cert_dir":     "/etc/letsencrypt/live/example.com",

    # enforcement / polling
    "poll_interval_sec": 120,

    # Monthly rollover of per-user traffic counters. Day of month (1-31) on which
    # every user's used_up/used_down is zeroed, mirroring the hosting provider's
    # own billing period so our accounting lines up with theirs.
    #   0  = follow the provider widget's reset date (provider.reset_field)
    #   1-31 = fixed day; clamped to the last day in shorter months
    # If 0 and the provider date is unavailable, the rollover is SKIPPED rather
    # than guessed — resetting on the wrong day is worse than resetting late.
    "traffic_reset_day": 0,

    # outbound link watchdog — TCP-connects to these external anycast IPs on a
    # tight cadence; all-fail => uplink packet-loss/blip (takes every protocol
    # down at once). IPs, not hostnames, so a DNS hiccup isn't misread as a link
    # outage.
    "outbound_probe_targets": ["1.1.1.1:443", "8.8.8.8:443", "9.9.9.9:443"],
    "outbound_probe_interval_sec": 30,

    # PARTIAL-outage detection. The anycast probe above only catches a TOTAL
    # uplink loss; a provider transit/peering fault can blackhole big chunks of
    # the internet (e.g. AWS-hosted Twitch, game servers) while Cloudflare/Google
    # anycast stay reachable — so the dashboard looks green while users can't
    # load anything. These are REAL, network-diverse service endpoints (different
    # clouds/CDNs); when >= reachability_alert_fails of them time out at once
    # while anycast is still up, that's a partial transit outage → TG alert.
    "reachability_targets": [
        "gql.twitch.tv:443",          # Twitch (AWS)
        "ec2.amazonaws.com:443",      # AWS baseline
        "www.youtube.com:443",        # Google
        "discord.com:443",            # Discord (chat)
        "store.steampowered.com:443",  # Steam (games)
        "www.microsoft.com:443",      # Microsoft / Azure
        "www.cloudflare.com:443",     # Cloudflare
    ],
    "reachability_alert_fails": 2,    # alert when >= this many targets unreachable
    "reachability_timeout_sec": 4,
}

# settings the web UI is allowed to persist (subset of keys above)
WEB_EDITABLE = {
    "brand", "domains", "sub_https_base", "sub_mirrors", "reality_sni",
    "hy2_up_mbps", "hy2_down_mbps", "admin_user", "admin_pass", "tg_bot_token",
    "host_thresholds", "user_thresholds", "provider", "traffic_reset_day",
}

# env var name -> (settings key, caster)
_ENV_MAP = {
    "BRAND": ("brand", str),
    "SERVER_IP": ("server_ip", str),
    "SUB_HTTPS_BASE": ("sub_https_base", str),
    "REALITY_PUBLIC_KEY": ("reality_public_key", str),
    "REALITY_PRIVATE_KEY": ("reality_private_key", str),
    "REALITY_SHORT_ID": ("reality_short_id", str),
    "REALITY_SNI": ("reality_sni", str),
    "REALITY_PORT": ("reality_port", int),
    "CDN_DOMAIN": ("cdn_domain", str),
    "DIRECT_DOMAIN": ("direct_domain", str),
    "HY2_SNI": ("hy2_sni", str),
    "TUIC_SNI": ("tuic_sni", str),
    "HU_PATH": ("hu_path", str),
    "HY2_PORT": ("hy2_port", int),
    "HY2_PORT_X": ("hy2_port_x", int),
    "TUIC_PORT": ("tuic_port", int),
    "TCP_PORT": ("tcp_port", int),
    "ADMIN_USER": ("admin_user", str),
    "ADMIN_PASS": ("admin_pass", str),
    "SECRET_KEY": ("secret_key", str),
    "HEALTH_TOKEN": ("health_token", str),
    "TG_BOT_TOKEN": ("tg_bot_token", str),
    "XRAY_CONTAINER": ("xray_container", str),
    "XRAY_API": ("xray_api", str),
    "SINGBOX_CONTAINER": ("singbox_container", str),
    "SINGBOX_CLASH_API": ("singbox_clash_api", str),
    "NGINX_CONTAINER": ("nginx_container", str),
    "CERT_DIR": ("cert_dir", str),
    "XRAY_CFG": ("xray_cfg", str),
    "SING_BOX_CFG": ("sing_box_cfg", str),
    "NGINX_CFG": ("nginx_cfg", str),
}

# JSON-valued env vars (parsed as JSON if present)
_ENV_JSON = {
    "DOMAINS": "domains",
    "SUB_MIRRORS": "sub_mirrors",
    "PROVIDER": "provider",
}


def _load_settings_file() -> dict:
    try:
        with open(SETTINGS_FILE) as f:
            return json.load(f)
    except Exception:
        return {}


def _apply_env(cfg: dict) -> None:
    for env, (key, cast) in _ENV_MAP.items():
        if env in os.environ and os.environ[env] != "":
            try:
                cfg[key] = cast(os.environ[env])
            except Exception:
                pass
    for env, key in _ENV_JSON.items():
        if env in os.environ and os.environ[env] != "":
            try:
                cfg[key] = json.loads(os.environ[env])
            except Exception:
                pass


class Settings:
    """Resolved settings snapshot. Access via attributes (cfg.server_ip)."""

    def __init__(self, data: dict):
        self._data = data

    def __getattr__(self, name):
        try:
            return self._data[name]
        except KeyError as e:
            raise AttributeError(name) from e

    def get(self, name, default=None):
        return self._data.get(name, default)

    def as_dict(self) -> dict:
        return dict(self._data)

    # ── convenience derived values ────────────────────────────────────────────
    def domain_by_role(self, role: str) -> str | None:
        for d in self._data.get("domains", []):
            if d.get("role") == role:
                return d["domain"]
        return None

    def reality_server_names(self) -> list[str]:
        """SNIs the 443 reality-steal inbound should accept (non-apex+apex)."""
        return [d["domain"] for d in self._data.get("domains", [])
                if d.get("role") in ("admin", "cdn", "direct", "apex")]

    def admin_base(self) -> str:
        """Public HTTPS base of the admin/panel (no trailing slash).

        Derived from sub_https_base (…/sub) so the Windows healthcheck reports
        through nginx-TLS on the admin domain instead of the raw :8080 port,
        which is firewalled off the internet. Falls back to the admin-role
        domain, then to http://IP:8080 for a not-yet-fronted bootstrap box.
        """
        base = (self._data.get("sub_https_base") or "").rstrip("/")
        if base.endswith("/sub"):
            base = base[:-4]
        if base:
            return base
        admin = self.domain_by_role("admin")
        if admin:
            return f"https://{admin}"
        ip = self._data.get("server_ip") or "127.0.0.1"
        return f"http://{ip}:8080"


def load() -> dict:
    cfg = json.loads(json.dumps(_DEFAULTS))  # deep copy
    _apply_env(cfg)
    # web-persisted overrides win, but only for the editable subset
    for k, v in _load_settings_file().items():
        if k in WEB_EDITABLE:
            cfg[k] = v
    return cfg


def save_web_settings(updates: dict) -> None:
    """Persist the web-editable subset to /data/settings.json (merge)."""
    os.makedirs(DATA_DIR, exist_ok=True)
    current = _load_settings_file()
    for k, v in updates.items():
        if k in WEB_EDITABLE:
            current[k] = v
    tmp = SETTINGS_FILE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(current, f, indent=2, ensure_ascii=False)
    os.replace(tmp, SETTINGS_FILE)
    get_settings.cache_clear()


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings(load())


def reload_settings() -> Settings:
    get_settings.cache_clear()
    return get_settings()
